### ISSUE TITLE
Just synths?

### ISSUE THREAD

**Issue by VegaDeftwing** [pencilresearch/midi#88]
Is the goal of this repo just to document synths, or are pedals/effects, controllers, etc. all wanted too?

If more is desired, it might be worth updating the README

**Comment by benjaminfox** [comment]
It's focused on synths, but all MIDI devices that use CCs are welcome.

**Comment by VegaDeftwing** [comment]
It may be worth lifting the database from https://github.com/Morningstar-Engineering/openmidi converted into the .csv format used, assuming license compatibility.

**Comment by benjaminfox** [comment]
Nice find! Thanks.
